export const FLAVOR_CATALOG = [
  { name: "Amaretto", unitWeight: 15.0 },
  { name: "Bananas Foster", unitWeight: 15.0 },
  { name: "Brownie Batter", unitWeight: 15.0 },
  { name: "Caramel Apple Cider", unitWeight: 15.0 },
  { name: "Champagne", unitWeight: 15.0 },
  { name: "Cheesecake", unitWeight: 14.9 },
  { name: "Confetti Cake", unitWeight: 15.0 },
  { name: "Cookies & Cream", unitWeight: 15.0 },
  { name: "Crème Brulée", unitWeight: 15.0 },
  { name: "Dulce de Leche", unitWeight: 15.0 },
  { name: "Espresso Martini", unitWeight: 15.2 },
  { name: "Grey Salt Caramel", unitWeight: 15.0 },
  { name: "Key Lime Pie", unitWeight: 15.0 },
  { name: "Lemon", unitWeight: 15.0 },
  { name: "Manhattan", unitWeight: 15.0 },
  { name: "Maple Cream", unitWeight: 15.0 },
  { name: "Peanut Butter Caramel", unitWeight: 15.0 },
  { name: "Pineapple Moscato", unitWeight: 15.0 },
  { name: "Pistachio", unitWeight: 15.0 },
  { name: "Pumpkin Spice Latte", unitWeight: 15.0 },
  { name: "Raspberry", unitWeight: 15.0 },
  { name: "S'Mores", unitWeight: 15.0 },
  { name: "Salted Caramel", unitWeight: 15.1 },
  { name: "Tea & Honey", unitWeight: 15.0 },
  { name: "Turtle", unitWeight: 15.0 },
];